-   id: habibilint
    name: habibilint
    description: '`habibilint` is a tool for linting python docstrings.'
    entry: habibilint
    language: python
    types: [python]
    require_serial: true
