.phony: all
all:
	docker build -t -36 -f Dockerfile.test36 . && \
	docker build -t -37 -f Dockerfile.test37 . && \
	docker build -t -38 -f Dockerfile.test38 . && \
	docker build -t -39 -f Dockerfile.test39 .
